In [31]:
import requests, time, tqdm, pandas, pickle

In [3]:
api = 'https://api.vk.com/method/'

token = '&access_token=21080f6aa0620f61794f27f0d064c09d19cb44cdd4183f591d5204c74bd5776eca4e41ac94f001f9b9f2a'
api = 'https://api.vk.com/method/'
app_token = '&access_token=a8e5b3eda8e5b3eda8e5b3ed43a8bae255aa8e5a8e5b3edf2e2da74f19ad53d539db181'

In [4]:
result = requests.get(api + 'database.getSchools?q=колледж&city_id=2&count=1000&v=5.69' + app_token)
json_result = result.json()

In [5]:
data = {}

In [6]:
kk = json_result['response']['items']

In [13]:
for item in tqdm.tqdm_notebook(kk):
    time.sleep(1)
    sers = requests.get(api + 'users.search' + '?count=1000&school=' + str(item['id']) + token).json()
    data[item['id']] = sers['response'][1:]
    #print(sers['response'][1:])

## Засовываем в пандас

In [27]:
data2 = {'first_name': [], 'last_name': [], 'uid': [], 'school': [], 'school_type': []}

for key, val in data.items():
    for info in val:
        data2['first_name'].append(info['first_name'])
        data2['last_name'].append(info['last_name'])
        data2['uid'].append(info['uid'])
        data2['school'].append(key)
        data2['school_type'].append(1)

In [28]:
frame = pandas.DataFrame(data2)
frame

       first_name           last_name  school  school_type        uid
0          Эдуард              Карлин  109826            1    3826297
1         Виталий             Кузьмин  109826            1  293941751
2          Руслан             Петикян  109826            1  190102307
3           Антон              Павлов  109826            1      48832
4      Александра              Жирова  109826            1   48592866
5       Анастасия           Завьялова  109826            1  108201924
6           Елена            Пузанова  109826            1   24042320
7           Павел              Болеев  109826            1   36571867
8         Оленька          Прокофьева  109826            1    3620120
9        Кристина            Туличева  109826            1  106504528
10          Елена             Иванова  109826            1  178404249
11         Ксения          Гончаренко  109826            1  153815591
12        Евгения          Семерикова  109826            1   67595467
13           Анна            Ульянова  109826            1    2742640
14         Victor       Alexandrovich  109826            1  169270861
15           Дима             Кузьмин  109826            1  156481293
16           Анна             Бузуева  109826            1   77234965
17        Алексей              Ефимов  109826            1   46297349
18         Регина             Киреева  109826            1    4305941
19           Anya          Cherkasova  109826            1  145953818
20          Лидия             Власова  109826            1  116187360
21         Виктор           Прокофьев  109826            1   60530019
22           Тома          Толстунова  109826            1   49486796
23         Марина           Анисимова  109826            1   14756583
24          Мария             Голосюк  109826            1    3714720
25           Вера               Зуева  109826            1    2157497
26          Дарья       Воскресенская  109826            1    1946596
27          Елена           Кунгурова  109826            1     697889
28         Сережа               Дикий  109826            1  190639326
29        Евдокия             Скрипач  109826            1  180251879
...           ...                 ...     ...          ...        ...
93181       Елена            Федорова   23294            1  364327977
93182     Наталья           Мартюкова   23294            1  363626128
93183        Анна          Николаевна   23294            1  327874498
93184          No                Name   23294            1  301457752
93185  Александра            Тарасова   23294            1  221034100
93186       Ирина           Николаева   23294            1  185581889
93187      Леонид           Кравченко   23294            1  162683499
93188      Наташа             Громова   23294            1  398263183
93189       Настя             Поршень   23294            1  352100627
93190   Анастасия           Михайлова   23294            1  340173980
93191       Елена              Гусева   23294            1  325634319
93192      Михаил              Злобин   23294            1  193274032
93193       Игорь             Светлых   23294            1  320971828
93194      Mental              Asylum   23294            1  149017583
93195       Анися            Ракедсон   23294            1  198396869
93196       Елена  Савина (Голоушина)   23294            1   10668017
93197     Валерия               Новак   23294            1  322438614
93198        Саша                Коша   23294            1  168893484
93199        Аида             Мамаева   23294            1  160902555
93200    Владимир          Алексеевич   23294            1  220637872
93201         Xri                 Xxx   23294            1  438047126
93202    Battsooj              Enhbat   23294            1  347916488
93203    Battsooj              Enhbat   23294            1  339220492
93204       Сария            Чепакова   23294            1  320460367
93205      Полина             Иванова   23294            1  319584065
93206      Valery           Saningong   23294            1  298534332
93207        Макс             Ангелов   23294            1  230574764
93208      Аленка          Безымянная   23294            1  197234652
93209     Мохамед            Неперсов   23294            1  176960527
93210        Hash              Knight   23294            1  169797987

[93211 rows x 5 columns]

# Пиклим все нафиг

In [32]:
with open('ptu_spb.pickle', 'wb') as f:
    pickle.dump(frame, f)