In [12]:
import pickle, pandas, requests, tqdm, time

In [13]:
with open('HS_spb.pickle', 'rb') as f:
    frame = pickle.load(f)

In [3]:
frame

       first_name       last_name  school  school_type        uid
0           Павел           Дуров       1            1          1
1         Дмитрий        Медведев       1            1   53083705
2           Ольга          Бузова       1            1   32707600
3          Марина          Кравец       1            1      30942
4             Ира             Ира       1            1      45376
5         Георгий        Лобушкин       1            1       3420
6       Александр          Жданов       1            1     668132
7         Дмитрий         Данилов       1            1       2022
8            Лена     Горностаева       1            1  266886437
9        Владимир           Путин       1            1  129186922
10         Сергей         Миронов       1            1   12086666
11            Боб            Джек       1            1    5036154
12         Даниил        Школьник       1            1    6858371
13      Елизавета     Туктамышева       1            1   38537529
14           Женя           Любич       1            1    3820053
15          Диана        Арбенина       1            1  290697449
16        Наргиза      Бандишоева       1            1  173109042
17         Андрей        Резников       1            1     697007
18          Мария          Орлова       1            1    1354011
19      Александр     Красовицкий       1            1      74211
20         Андрей           Рябых       1            1  164094477
21          Артур     Парфенчиков       1            1  419407976
22      Александр          Цыпкин       1            1     680751
23         Мистер           Малой       1            1   19030619
24          Артем          Балаев       1            1    1826463
25           Юлия     Барановская       1            1  265883543
26       Кристина       Степанова       1            1   18927336
27         Кирилл         Соколов       1            1   95719550
28         Михаил      Захаренков       1            1        175
29      Анастасия       Виленская       1            1  314042609
...           ...             ...     ...          ...        ...
161223       Maks         Smirnov  244981            1  178696485
161224     Андрей         Сергеев  244981            1   28010009
161225    Людимла        Еремеева  244981            1  230092585
161226     Любовь        Гулимова  244981            1  204347079
161227      Alice           Glass  244981            1   88555531
161228       Дима          Петров  244981            1   22421851
161229     Наташа         Иванова  244981            1    4769245
161230      Тимур         Рыбаков  244981            1  155293069
161231       Юрий          Радаев  244981            1  141500080
161232        Leo           Stain  244981            1  373138936
161233       Женя         Фролова  244981            1  371419708
161234      Злата         Егорова  244981            1  354657370
161235     Любовь        Летягина  244981            1  326924437
161236     Кирилл         Андреич  244981            1  273152265
161237      Федор       Милорадов  244981            1  387015312
161238     Фарход           Норов  244981            1  233221799
161239       Петя        Васильев  244981            1  202759984
161240     Эдуард         Кузьмин  244981            1  141910428
161241      Арина         Бойкова  244981            1   49359619
161242      Елена       Кириллова  244981            1  327854620
161243    Дмитрий        Кузнецов  244981            1  309192470
161244      Мария         Иванова  244981            1  155415381
161245      Анюта          Вредня  244981            1  373272637
161246    Татьяна   Морскаятабола  244981            1  193384775
161247      Дарья        Абрамова  244981            1  151279031
161248    Евгений       Блинников  244981            1  305397774
161249      Takoi             Vot  244981            1  168878856
161250      Елена       Онгороева  244981            1  213284539
161251      Малик  Гаджимагомедов  244981            1  184340110
161252    Алексей           Котов  244981            1  108410521

[161253 rows x 5 columns]

In [14]:
uids = list(frame['uid'])

def chunks(lst, chunk_size):
    return [lst[i:i + chunk_size] for i in range(0, len(lst), chunk_size)]

uids = chunks(uids, 24)

In [15]:
api = 'https://api.vk.com/method/'

token = '&access_token=5282c72f5b418a94820f3efa69a6ebb8c748f700e193b91600a488345749391afe7f6b3ad1f0f9d4db2dc'
api = 'https://api.vk.com/method/'
app_token = '&access_token=a8e5b3eda8e5b3eda8e5b3ed43a8bae255aa8e5a8e5b3edf2e2da74f19ad53d539db181'

In [16]:
data = {
    'sex': [], 'has_photo': [], 'relation': [],
    'political': [], 'religion': [], 'people_main': [], 'life_main': [],
    'smoking': [], 'alchol': [], 'groups': []
}

In [18]:
for uid in tqdm.tqdm_notebook(uids):
    time.sleep(0.3)
    #print(uid)
    sers = requests.get(api + 'execute.getInfoo' + '?idd=' + ','.join(list(map(str, uid))) + token).json()
    
    groups = sers['response'][0]
    #print(groups[1][1]['gid'])
    get = sers['response'][1][0]
    if type(groups) == type(False):
        print(groups)
    for user in groups:
        tmp = []
        if type(user) == type(False):
            data['groups'].append([])
            continue
        for group in user:
            tmp.append(group.setdefault('gid', None))
        data['groups'].append(tmp)
        
    for x in get:
        data['sex'].append(x['sex'])
        data['has_photo'].append(x.setdefault('has_photo', None))
        data['religion'].append(x.setdefault('personal', {}).setdefault('religion', None))
        data['relation'].append(x.setdefault('relation', None))
        data['political'].append(x.setdefault('personal', {}).setdefault('political', None))
        data['people_main'].append(x.setdefault('personal', {}).setdefault('people_main', None))
        data['life_main'].append(x.setdefault('personal', {}).setdefault('life_main', None))
        data['smoking'].append(x.setdefault('personal', {}).setdefault('smoking', None))
        data['alchol'].append(x.setdefault('personal', {}).setdefault('alcohol', None))

### бинаризируем, засовываем в пандас и пикалим

In [36]:
import pickle
with open('data_HS.pickle', 'wb') as f:
    pickle.dump(data, f)

In [37]:
a = pandas.DataFrame(data)

In [38]:
result = pandas.concat([frame, a], axis = 1, join_axes = [frame.index])

In [46]:
import pickle
result['school_type'] = 2
with open('data_HS_main.pickle', 'wb') as f:
    pickle.dump(data, f)